# Setup
title:               Petite Brewery Blog
tagline:             ''
description:         'Sharing my brewing and entrepreneurship experience'
url:                 https://neiram44.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Marien
  url:               https://twitter.com/petitebrewery
  email:             marien@petitebrouerie.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
